## 4. Producto de criptosistemas de permutación

In [10]:
import numpy as np

In [11]:
def read_input(i):
    # Primero tomamos el input de i o de la entrada estándar
    if i==0:
        cadena=input()
    else:
        file=open(i, "r")
        cadena=file.read()
        file.close()
    print("Cadena: {}".format(cadena))
    return cadena

In [12]:
def print_output(o,cadena):
    if o==0:
        print("Cadena: {}".format(cadena))
    else:
        file=open(o, "w")
        cadenaToStr = ' '.join([str(elem) for elem in cadena])
        file.write(cadenaToStr)
        file.close()

In [13]:
#Traducimos los caracteres a números
            cadena_numerica=[]
            for k in cadena:
                if k in alfabeto: 
                    cadena_numerica.append(alfabeto.index(k))
                    
            # Dividimos en bloques de n elementos el texto
            # Si m no es múltiplo de n se añade padding
            m=len(cadena_numerica)/n
            max=len(cadena_numerica)
            matriz_numerica=np.zeros((math.ceil(m),n))
         
            pos=0
            for i in range(math.ceil(m)):
                for j in range(n):
                    if pos<max:
                        matriz_numerica[i][j]=cadena_numerica[pos]
                        pos=pos+1
                        
            #ciframos cadena a cadena y lo guardamos en un matriz           
            matriz_cifrada=cifrar(matriz_numerica,matriz,mod,n)
            print_output(o,matriz_cifrada)

IndentationError: unexpected indent (Temp/ipykernel_4208/2791839882.py, line 2)

In [26]:
# k1: vector de m elementos que constituye la clave para el cifrado de permutación por filas
# k2: vector de n elementos que constituye la clave para el cifrado de permutación por columnas
def permutacion(modo,k1,k2,i=0,o=0):
    alfabeto='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'
    if modo=="-C":
        cadena=read_input(i)
        # Traducimos los caracteres a números
        cadena_numerica=[]
        for k in cadena:
            if k in alfabeto: 
                cadena_numerica.append(alfabeto.index(k))

        # Matriz numerica es la matriz m x n 
        m=len(k1)
        n=len(k2)
        maxi=len(cadena_numerica)
        matriz_numerica=np.zeros((m,n))
         
        pos=0
        for i in range(m):
            for j in range(n):
                if pos<maxi:
                    matriz_numerica[i][j]=cadena_numerica[pos]
                    pos=pos+1
        print(matriz_numerica)
        
        # Cifrado de permutación por filas
        matriz_cifrada1=np.zeros((m,n))
        for i in range(m):
            for j in range(n):
                matriz_cifrada1[i][j]=matriz_numerica[k1[i]][j]
        print(matriz_cifrada1)
                
        # Cifrado de permutación por columnas
        matriz_cifrada2=np.zeros((m,n))
        for i in range(m):
            for j in range(n):
                matriz_cifrada2[i][j]=matriz_cifrada1[i][k2[j]]
                
        print(matriz_cifrada2)
        print_output(o, matriz_cifrada2)
    elif modo=="-D":
        cadena_cifrada=read_input(i)
        cadena_cifrada=cadena_cifrada.split(" ")
        
         # Matriz numerica es la matriz m x n 
        m=len(k1)
        n=len(k2)
        maxi=len(cadena_cifrada)
        matriz_cifrada=np.zeros((m,n))
         
        pos=0
        for i in range(m):
            for j in range(n):
                if pos<maxi:
                    matriz_cifrada[i][j]=cadena_cifrada[pos]
                    pos=pos+1
        print(matriz_cifrada)
        
        # Desciframos cifrado de permutación por columnas
        matriz_descifrada2=np.zeros((m,n))
        for i in range(m):
            for j in range(n):
                matriz_descifrada2[i][k2[j]]=matriz_cifrada[i][j]
        
        print(matriz_descifrada2)
        
        # Desciframos cifrado de permutación por filas
        matriz_descifrada1=np.zeros((m,n))
        for i in range(m):
            for j in range(n):
                matriz_descifrada1[k1[i]][j]=matriz_descifrada2[i][j]
        print(matriz_descifrada1)
        
        cadena_descifrada=np.concatenate(matriz_descifrada1)
        cadena_texto=[]
        for i in range(len(cadena_descifrada)):
            #cadena_cifrada[i]=int(cadena_cifrada[i])
            cadena_texto.append(alfabeto[int(cadena_descifrada[i])])

        print_output(o, cadena_texto)

In [17]:
k1=[3,2,4,1,0]
k2=[1,3,2,0]
permutacion("-C", k1, k2)

Buenos dias
Cadena: Buenos dias
[[27. 20.  4. 13.]
 [14. 18.  3.  8.]
 [ 0. 18.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 0.  0.  0.  0.]
 [ 0. 18.  0.  0.]
 [ 0.  0.  0.  0.]
 [14. 18.  3.  8.]
 [27. 20.  4. 13.]]
[[ 0.  0.  0.  0.]
 [18.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [18.  8.  3. 14.]
 [20. 13.  4. 27.]]
Cadena: [[ 0.  0.  0.  0.]
 [18.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [18.  8.  3. 14.]
 [20. 13.  4. 27.]]


In [27]:
permutacion("-D", k1, k2)

0 0 0 0 18 0 0 0 0 0 0 0 18 8 3 14 20 13 4 27
Cadena: 0 0 0 0 18 0 0 0 0 0 0 0 18 8 3 14 20 13 4 27
[[ 0.  0.  0.  0.]
 [18.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [18.  8.  3. 14.]
 [20. 13.  4. 27.]]
[[ 0.  0.  0.  0.]
 [ 0. 18.  0.  0.]
 [ 0.  0.  0.  0.]
 [14. 18.  3.  8.]
 [27. 20.  4. 13.]]
[[27. 20.  4. 13.]
 [14. 18.  3.  8.]
 [ 0. 18.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
Cadena: ['B', 'u', 'e', 'n', 'o', 's', 'd', 'i', 'a', 's', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a']
