## 4. Producto de criptosistemas de permutación

In [2]:
import numpy as np

In [3]:
def read_input(i):
    # Primero tomamos el input de i o de la entrada estándar
    if i==0:
        cadena=input()
    else:
        file=open(i, "r")
        cadena=file.read()
        file.close()
    print("Cadena: {}".format(cadena))
    return cadena

In [4]:
def print_output(o,cadena):
    if o==0:
        print("Cadena: {}".format(cadena))
    else:
        file=open(o, "w")
        cadenaToStr = ' '.join([str(elem) for elem in cadena])
        file.write(cadenaToStr)
        file.close()

In [5]:
# k1: vector de m elementos que constituye la clave para el cifrado de permutación por filas
# k2: vector de n elementos que constituye la clave para el cifrado de permutación por columnas
def permutacion(modo,k1,k2,i=0,o=0):
    alfabeto='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'
    if modo=="-C":
        cadena=read_input(i)
        # Traducimos los caracteres a números
        cadena_numerica=[]
        for k in cadena:
            if k in alfabeto: 
                cadena_numerica.append(alfabeto.index(k))

        # Matriz numerica es la matriz m x n 
        m=len(k1)
        n=len(k2)
        maxi=len(cadena_numerica)
        matriz_numerica=np.zeros((m,n))
         
        pos=0
        for i in range(m):
            for j in range(n):
                if pos<maxi:
                    matriz_numerica[i][j]=cadena_numerica[pos]
                    pos=pos+1
        print(matriz_numerica)
        
        # Cifrado de permutación por filas
        matriz_cifrada1=np.zeros((m,n))
        for i in range(m):
            for j in range(n):
                matriz_cifrada1[i][j]=matriz_numerica[k1[i]][j]
        print(matriz_cifrada1)
                
        # Cifrado de permutación por columnas
        matriz_cifrada2=np.zeros((m,n))
        for i in range(m):
            for j in range(n):
                matriz_cifrada2[i][j]=matriz_cifrada1[i][k2[j]]
                
        print(matriz_cifrada2)
        print_output(o, matriz_cifrada2)
    elif modo=="-D":
        cadena_cifrada=read_input(i)
        cadena_cifrada=cadena_cifrada.split(" ")
        
         # Matriz numerica es la matriz m x n 
        m=len(k1)
        n=len(k2)
        maxi=len(cadena_cifrada)
        matriz_cifrada=np.zeros((m,n))
         
        pos=0
        for i in range(m):
            for j in range(n):
                if pos<maxi:
                    matriz_cifrada[i][j]=cadena_cifrada[pos]
                    pos=pos+1
        print(matriz_cifrada)
        
        # Desciframos cifrado de permutación por columnas
        matriz_descifrada2=np.zeros((m,n))
        for i in range(m):
            for j in range(n):
                matriz_descifrada2[i][k2[j]]=matriz_cifrada[i][j]
        
        print(matriz_descifrada2)
        
        # Desciframos cifrado de permutación por filas
        matriz_descifrada1=np.zeros((m,n))
        for i in range(m):
            for j in range(n):
                matriz_descifrada1[k1[i]][j]=matriz_descifrada2[i][j]
        print(matriz_descifrada1)
        
        cadena_descifrada=np.concatenate(matriz_descifrada1)
        cadena_texto=[]
        for i in range(len(cadena_descifrada)):
            #cadena_cifrada[i]=int(cadena_cifrada[i])
            cadena_texto.append(alfabeto[int(cadena_descifrada[i])])

        print_output(o, cadena_texto)

In [6]:
k1=[3,2,4,1,0]
k2=[1,3,2,0]
permutacion("-C", k1, k2)

Universidad Autonoma de Madrid
Cadena: Universidad Autonoma de Madrid
[[46. 13.  8. 21.]
 [ 4. 17. 18.  8.]
 [ 3.  0.  3. 26.]
 [20. 19. 14. 13.]
 [14. 12.  0.  3.]]
[[20. 19. 14. 13.]
 [ 3.  0.  3. 26.]
 [14. 12.  0.  3.]
 [ 4. 17. 18.  8.]
 [46. 13.  8. 21.]]
[[19. 13. 14. 20.]
 [ 0. 26.  3.  3.]
 [12.  3.  0. 14.]
 [17.  8. 18.  4.]
 [13. 21.  8. 46.]]
Cadena: [[19. 13. 14. 20.]
 [ 0. 26.  3.  3.]
 [12.  3.  0. 14.]
 [17.  8. 18.  4.]
 [13. 21.  8. 46.]]


In [7]:
permutacion("-D", k1, k2)

19. 13. 14. 20. 0. 26. 3. 3. 12. 3. 0. 14. 17. 8. 18. 4. 13. 21. 8. 46.
Cadena: 19. 13. 14. 20. 0. 26. 3. 3. 12. 3. 0. 14. 17. 8. 18. 4. 13. 21. 8. 46.
[[19. 13. 14. 20.]
 [ 0. 26.  3.  3.]
 [12.  3.  0. 14.]
 [17.  8. 18.  4.]
 [13. 21.  8. 46.]]
[[20. 19. 14. 13.]
 [ 3.  0.  3. 26.]
 [14. 12.  0.  3.]
 [ 4. 17. 18.  8.]
 [46. 13.  8. 21.]]
[[46. 13.  8. 21.]
 [ 4. 17. 18.  8.]
 [ 3.  0.  3. 26.]
 [20. 19. 14. 13.]
 [14. 12.  0.  3.]]
Cadena: ['U', 'n', 'i', 'v', 'e', 'r', 's', 'i', 'd', 'a', 'd', 'A', 'u', 't', 'o', 'n', 'o', 'm', 'a', 'd']
